
import React, { useState } from 'react';
import { AdminLayout } from '@/components/admin/AdminLayout';
import { ProjectStatsOverview } from '@/components/admin/project/ProjectStatsOverview';
import ProjectParametersList from '@/components/admin/project/ProjectParametersList';
import { NewPartnerForm } from '@/components/admin/project/NewPartnerForm';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ProjectParameter } from '@/types/project';

const ProjectAdmin = () => {
  // Sample project statistics
  const projectStats = {
    totalUsers: 1240,
    activeUsers: 892,
    totalTokens: 20000,
    tokenCirculation: 16400,
    averageYield: 11.2,
    harvestFrequency: 'Quarterly',
    totalFarms: 1,
    totalTokenHolders: 872,
    totalHectares: 20,
    projectValue: 600000
  };

  // Sample project parameters for demo
  const [parameters, setParameters] = useState<ProjectParameter[]>([
    {
      id: '1',
      name: 'Initial Token Price',
      description: 'The price of a single vanilla plant token at launch',
      value: '30',
      category: 'financial',
      lastUpdated: '2023-06-15T10:30:00Z'
    },
    {
      id: '2',
      name: 'Target Yield',
      description: 'Annual yield target for token holders from harvest',
      value: '12',
      category: 'financial',
      lastUpdated: '2023-07-22T14:15:00Z'
    },
    {
      id: '3',
      name: 'Harvest Revenue Share',
      description: 'Percentage of harvest revenue distributed to token holders',
      value: '80',
      category: 'financial',
      lastUpdated: '2023-08-05T09:45:00Z'
    },
    {
      id: '4',
      name: 'Vanilla Species',
      description: 'The species of vanilla being cultivated on the farm',
      value: 'Vanilla planifolia',
      category: 'agricultural',
      lastUpdated: '2023-05-10T16:20:00Z'
    },
    {
      id: '5',
      name: 'Planting Density',
      description: 'Number of vanilla plants per hectare',
      value: '1000',
      category: 'operational',
      lastUpdated: '2023-09-18T11:10:00Z'
    },
    {
      id: '6',
      name: 'Farm Size',
      description: 'Total area of the vanilla farm in hectares',
      value: '20',
      category: 'agricultural',
      lastUpdated: '2023-04-30T13:25:00Z'
    },
    {
      id: '7',
      name: 'Carbon Credits',
      description: 'Annual carbon credits generated by farm operations',
      value: '500',
      category: 'agricultural',
      lastUpdated: '2023-10-12T15:40:00Z'
    },
    {
      id: '8',
      name: 'DAO Voting Threshold',
      description: 'Minimum percentage of votes needed for proposal approval',
      value: '60',
      category: 'governance',
      lastUpdated: '2023-11-25T10:05:00Z'
    }
  ]);

  // Handle parameter updates
  const handleParameterUpdate = (updatedParameter: ProjectParameter) => {
    setParameters(parameters.map((param) =>
      param.id === updatedParameter.id ? updatedParameter : param
    ));
  };

  return (
    <AdminLayout title="Project Administration">
      <Tabs defaultValue="overview" className="space-y-6">
        <TabsList className="bg-earth-700">
          <TabsTrigger value="overview" className="data-[state=active]:bg-earth-600">Overview</TabsTrigger>
          <TabsTrigger value="parameters" className="data-[state=active]:bg-earth-600">Parameters</TabsTrigger>
          <TabsTrigger value="partners" className="data-[state=active]:bg-earth-600">Partners</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="space-y-6">
          <ProjectStatsOverview stats={projectStats} />
          <div className="bg-earth-800/50 rounded-xl p-6">
            <h2 className="text-xl font-medium text-vanilla-100 mb-4">Recent Project Updates</h2>
            <p className="text-vanilla-300">
              This section will display recent changes and updates to the project. Future development will include 
              an activity feed showing parameter changes, partnership announcements, and governance decisions.
            </p>
          </div>
        </TabsContent>

        <TabsContent value="parameters" className="space-y-6">
          <div className="bg-earth-800/50 rounded-xl p-6 mb-6">
            <h2 className="text-xl font-medium text-vanilla-100 mb-4">Project Parameters</h2>
            <p className="text-vanilla-300 mb-4">
              These parameters define the core attributes and performance metrics of the vanilla farming project. 
              Updates to these values will be reflected across the platform and communicated to stakeholders.
            </p>
          </div>
          <ProjectParametersList 
            parameters={parameters} 
            onUpdate={handleParameterUpdate} 
          />
        </TabsContent>

        <TabsContent value="partners" className="space-y-6">
          <div className="bg-earth-800/50 rounded-xl p-6 mb-6">
            <h2 className="text-xl font-medium text-vanilla-100 mb-4">Project Partners</h2>
            <p className="text-vanilla-300 mb-4">
              Manage partnerships with organizations that contribute to the Vanilla Valley ecosystem. 
              Add new partners to showcase on the platform and in marketing materials.
            </p>
          </div>
          <NewPartnerForm />
        </TabsContent>
      </Tabs>
    </AdminLayout>
  );
};

export default ProjectAdmin;
